export enum TIPS {
  EXPANS = "expans",
  TERRAIN = "terrain",
  WIGHLD = "wighld",
  ATTERRISSAGE = "aterrissage",
  ATTERRISSAGE_REUSSI = "aterrissage-reussi",
  HOL_ZONG = "hol-zong",
  CONNEXION_REQUISE = "connexion-requise",
  GENERATION_IDEES = "generation-idees",
  TRANSFERT_IDEES = "transfert-idees",
  BRULURE = "brulure",
  CONNEXION_ETABLIE = "connexion-etablie",
  PREMIERS_PAS = "premiers-pas",
  NOYAUX_DE_DONNEES = "noyaux-de-donnees",
  BATIMENTS = "batiments",
}
